# Generated by Django 3.2 on 2021-07-07 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('state_city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_title', models.CharField(max_length=80)),
                ('comp_desc', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=20)),
                ('status', models.CharField(default='not started', max_length=20)),
                ('action_taken', models.CharField(default='none', max_length=90)),
                ('progress', models.IntegerField(default=0)),
                ('comp_date', models.DateField(auto_now=True)),
                ('comp_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('comp_video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('city_id', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, to='state_city.cities')),
                ('comp_by', models.ForeignKey(db_column='comp_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('state_id', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='state_city.states')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
