# Generated by Django 3.2 on 2021-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_auto_20210706_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
